import Head from "next/head";

import Layout from "~/layout";
import Banner from "~/components/Banner";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>

                <section className="relative flex justify-center items-center w-full min-h-screen flex-col py-[35px] md:py-[54px] font-thunder">
                    <Banner />
                </section>
                
            </Layout>
        </>
    );
}
