import Head from "next/head";

import FetchLoader from "~/components/loaders/FetchLoader";
import Navbar from "~/components/Navbar";
import ProtectedRoute from "~/components/ProtectedRoute";
import TodoList from "~/components/TodoList";
import Layout from "~/layout";
import { useLoginStore } from "~/store/login";
import { getStaticProps } from "~/utils";

export default function Home() {
    const {message, apiLoading} = useLoginStore();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Navbar />

                <ProtectedRoute redirect='login'>
                    {
                        apiLoading ? 
                            <FetchLoader message={message} /> :
                            <TodoList />
                    }
                </ProtectedRoute>
            </Layout>
        </>
    );
}

export { getStaticProps };