name: CI

on: [push, pull_request]

env:
    DATABASE_URL: "https://fake.com"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14 # You can specify your desired Node.js version

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: Typecheck
              run: pnpm run typecheck

            - name: Lint
              run: pnpm run lint

            - name: Print Environment Variable
              run: echo $MY_ENV_VAR
